name: Build Godot 4.4 Double Precision
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: windows-2022
 
    steps:
      - name: Checkout Godot source
        uses: actions/checkout@v3
 
      - name: Install dependencies
        run: |
          choco install -y python3 scons git
        shell: powershell
 
      - name: Clone Godot 4.4
        run: git clone --branch 4.4-stable https://github.com/godotengine/godot.git godot
 
      - name: Build Godot editor (double precision)
        run: |
          cd godot
          python3 -m pip install --upgrade pip
          scons platform=windows target=editor arch=x86_64 precision=double -j %NUMBER_OF_PROCESSORS%
        shell: cmd
 
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: godot-double-windows
          path: godot\bin\godot.windows.editor.x86_64.double.exe